import { z } from 'zod/mini';
import type { Settings } from '../types';
import { assertNoDrift } from './drift';
import { quoteCategorySchema } from './quotes';

/**
 * Every field of `Settings`, which is the one stored blob whose shape the whole UI reads
 * without checking. `assertNoDrift` below is what keeps it honest: adding a setting to the
 * interface without adding it here stops compiling.
 */
export const settingsSchema = z.object({
  pomodoroWorkDuration: z.number(),
  pomodoroBreakDuration: z.number(),
  pomodoroLongBreakDuration: z.number(),
  pomodoroLongBreakInterval: z.number(),
  pomodoroAutoStartBreaks: z.boolean(),
  pomodoroAmbientSound: z.string(),
  pomodoroAmbientVolume: z.number(),
  pomodoroStartSound: z.string(),
  pomodoroCompletionSound: z.string(),
  pomodoroMusicEnabled: z.boolean(),
  pomodoroMusicVolume: z.number(),
  pomodoroMusicAutoStart: z.boolean(),
  pomodoroMusicPlaylistId: z.string(),
  pomodoroMusicPlayDuringBreaks: z.boolean(),
  pomodoroCompanion: z.enum(['quote', 'calendar', 'both']),
  enableNotifications: z.boolean(),
  theme: z.enum(['light', 'dark', 'auto']),
  quoteChangeInterval: z.number(),
  timeFormat: z.enum(['12h', '24h']),
  syncEnabled: z.boolean(),
  colorTheme: z.enum(['purple', 'forest', 'rose', 'glass']),
  glassEnhanced: z.boolean(),
  backgroundDim: z.number(),
  backgroundBlur: z.number(),
  layoutDensity: z.enum(['compact', 'comfortable', 'spacious']),
  showThemeSwitcher: z.boolean(),
  showClock: z.boolean(),
  showQuickLinks: z.boolean(),
  showNotes: z.boolean(),
  note: z.string(),
  notesExpanded: z.boolean(),
  notesPinned: z.boolean(),
  showWeather: z.boolean(),
  weatherPosition: z.enum(['left', 'right']),
  weatherUnits: z.enum(['auto', 'metric', 'imperial']),
  enableGoalTransfer: z.boolean(),
  goalTransferTime: z.number(),
  autoRollDueTasks: z.boolean(),
  logLevel: z.enum(['none', 'error', 'warn', 'info', 'debug']),
  hasSeenOnboarding: z.boolean(),
  focusModeEnabled: z.boolean(),
  focusModeImageCategory: z.enum(['nature', 'forest', 'ocean', 'mountains', 'minimal', 'dark']),
  focusModeShowQuote: z.boolean(),
  focusModeShowGoal: z.boolean(),
  focusModeAutoEnter: z.boolean(),
  goalViewMode: z.enum(['full', 'compact', 'focus']),
  newTabShowCalendar: z.boolean(),
  newTabCalendarPosition: z.enum(['above', 'below']),
  focusedGoalId: z.nullable(z.string()),
  showCompletedGoals: z.boolean(),
  showIncompleteGoals: z.boolean(),
  showUpcomingGoals: z.boolean(),
  quoteDisplayMode: z.enum(['normal', 'compact', 'bottom', 'hidden']),
  enableQuoteAnimation: z.boolean(),
  focusPosition: z.enum(['top', 'center', 'bottom']),
  quoteFilterEnabledCategories: z.array(quoteCategorySchema),
  quoteFilterShowCustomQuotes: z.boolean(),
  quoteFilterShowFavoritesOnly: z.boolean(),
  quoteFilterActiveCollectionIds: z.array(z.string()),
  celebrationsEnabled: z.boolean(),
  reminderPanelLayout: z.enum(['composed', 'agenda']),
  reminderPanelPinned: z.boolean(),
  reviewPromptDismissed: z.boolean(),
  reviewPromptCount: z.number(),
  reviewPromptLastShownAt: z.nullable(z.string()),
  conceptCardsEnabled: z.boolean(),
  conceptCadence: z.enum(['every', 'third', 'ten', 'off']),
  conceptFraming: z.enum(['ambient', 'queue']),
  conceptActiveRecall: z.boolean(),
  conceptNudgeDismissed: z.boolean(),
  conceptNudgeCount: z.number(),
  conceptNudgeLastShownAt: z.nullable(z.string()),
});
assertNoDrift<z.infer<typeof settingsSchema>, Settings>();
