// @cuewise/storage public API — explicit named exports (no wildcard barrels),
// so the surface is reviewable and can't leak internals or collide.

// KeyValueStore adapters (implement the platform port)
export { ChromeKeyValueStore } from './chrome-key-value-store';
export type { StorageArea, StorageError, StorageErrorType, StorageResult } from './chrome-storage';
// Low-level storage delegators over the platform port
export {
  getFromStorage,
  getManyFromStorage,
  removeFromStorage,
  removeManyFromStorage,
  setInStorage,
  setManyInStorage,
} from './chrome-storage';
export { LocalStorageKeyValueStore } from './local-storage-key-value-store';
export type { PlaylistResumeInfo, SettingsRead, StorageUsageInfo } from './storage-helpers';
// Typed storage helpers
export {
  clearCustomBackground,
  clearSettings,
  ensureSettingsMigrated,
  formatBytes,
  getCalendarState,
  getCollections,
  getCollectionsRaw,
  getConceptCards,
  getCurrentQuote,
  getCurrentVideoForPlaylist,
  getCustomBackground,
  getCustomYoutubePlaylists,
  getDailyBackground,
  getGoals,
  getGoalsRaw,
  getPomodoroSessions,
  getPomodoroSessionsRaw,
  getPostureStats,
  getQuickLinks,
  getQuotes,
  getQuotesRaw,
  getReminders,
  getRemindersRaw,
  getSettings,
  getSettingsForSync,
  getStorageUsage,
  getWeatherState,
  getYoutubeProgress,
  isCustomQuote,
  migrateLegacySettings,
  migrateStorageData,
  readSettings,
  SETTINGS_KEY_PREFIX,
  SETTINGS_KEYS,
  setCalendarState,
  setCollections,
  setCollectionsRaw,
  setConceptCards,
  setCurrentQuote,
  setCustomBackground,
  setCustomYoutubePlaylists,
  setDailyBackground,
  setGoals,
  setGoalsRaw,
  setPomodoroSessions,
  setPomodoroSessionsRaw,
  setPostureStats,
  setQuickLinks,
  setQuotes,
  setQuotesRaw,
  setReminders,
  setRemindersRaw,
  setSettingsPatch,
  setSettingsPatchRaw,
  settingsStorageKey,
  setWeatherState,
  updateVideoProgress,
} from './storage-helpers';
