packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.5
  '@crxjs/vite-plugin': ^2.2.1
  '@tailwindcss/postcss': ^4.1.17
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.1.0
  '@testing-library/user-event': ^14.5.2
  '@types/chrome': ^0.1.29
  '@types/react': ^18.3.26
  '@types/react-dom': ^18.3.7
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/ui': ^3.2.0
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  date-fns: ^4.1.0
  fishery: ^2.2.2
  jsdom: ^25.0.1
  lucide-react: ^0.553.0
  postcss: ^8.5.6
  react: ^18.3.1
  react-dom: ^18.3.1
  recharts: 2.15.4
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  turbo: ^2.6.1
  typescript: ^5.9.3
  vite: ^6.0.7
  vitest: 3.2.4
  zustand: 5.0.8

onlyBuiltDependencies:
  - esbuild
