packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild

catalog:
  # Build tools
  vite: ^6.0.7
  '@vitejs/plugin-react': ^5.1.1
  '@crxjs/vite-plugin': ^2.2.1

  # Styling
  tailwindcss: ^4.1.17
  '@tailwindcss/postcss': ^4.1.17
  postcss: ^8.5.6
  autoprefixer: ^10.4.20
  tailwind-merge: ^3.4.0

  # React
  react: ^18.3.1
  'react-dom': ^18.3.1
  '@types/react': ^18.3.26
  '@types/react-dom': ^18.3.7

  # State & Icons
  zustand: ^5.0.8
  lucide-react: ^0.553.0
  clsx: ^2.1.1

  # Utilities
  date-fns: ^4.1.0

  # TypeScript & Tooling
  typescript: ^5.9.3
  '@types/chrome': ^0.1.29
  '@biomejs/biome': ^2.3.5
  turbo: ^2.6.1
