// design-sync: prepare build inputs for the CueWise UI design bundle.
//   1. Compile the Tailwind v4 stylesheet (tokens + theme + utilities) the
//      converter copies into _ds_bundle.css.
//   2. Generate a clean bundle entry that re-exports @cuewise/ui's components
//      WITHOUT the `styles.css?inline` export — esbuild can't bundle that
//      Tailwind import, and the design bundle handles CSS separately.
// Both outputs land in packages/ui/dist/ (gitignored, inside the package so
// design-sync's path containment accepts them). buildCmd re-runs this on every
// re-sync, so the artifacts are reproducible and never committed.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const outDir = resolve(repoRoot, 'packages/ui/dist');
mkdirSync(outDir, { recursive: true });

// ── 1. compile CSS ─────────────────────────────────────────────────────────
const extReq = createRequire(resolve(repoRoot, 'apps/browser-extension/package.json'));
const postcss = extReq('postcss');
const tailwind = extReq('@tailwindcss/postcss');

const cssIn = resolve(here, 'ds-tailwind.src.css');
const cssOut = resolve(outDir, 'cuewise.css');
// Brand fonts ship via Google Fonts in the extension's index.html, not the CSS.
// Prepend the same @import (leading @import is always valid) so design-bundle
// previews render in the real Inter/Poppins instead of a fallback face.
const FONT_IMPORT =
  "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Poppins:wght@600;700;800&display=swap');\n";
const cssResult = await postcss([tailwind()]).process(readFileSync(cssIn, 'utf8'), {
  from: cssIn,
  to: cssOut,
});
const css = FONT_IMPORT + cssResult.css;
writeFileSync(cssOut, css);
console.log(`compiled css: ${css.length} bytes -> ${cssOut}`);

// ── 2. generate the bundle entry ────────────────────────────────────────────
const indexSrc = readFileSync(resolve(repoRoot, 'packages/ui/src/index.ts'), 'utf8');
const entryLines = indexSrc
  .split('\n')
  .filter((l) => /\bfrom\s+['"]\.\//.test(l)) // re-export lines only
  .filter((l) => !l.includes('.css')) // drop the styles.css?inline export
  .map((l) => l.replace(/(['"])\.\//, '$1../src/')); // dist/ -> ../src/
const entryOut = resolve(outDir, 'ds-entry.mjs');
writeFileSync(
  entryOut,
  `// generated by .design-sync/prepare.mjs — do not edit\n${entryLines.join('\n')}\n`
);
console.log(`generated entry: ${entryLines.length} re-exports -> ${entryOut}`);
